name: Update whitelist

on:
  push:
    paths: [".github/workflows/**", "src/**"]
  pull_request:
    paths: [".github/workflows/**", "src/**"]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check source files
        shell: bash
        run: |
          for file in $(find src -type f -print); do
            if [[ "${file##*.}" != "txt" ]]; then
              >&2 echo "[warning] The extension of ${file} is not txt."
              >&2 echo "          This file will be ignored."
            elif [[ $(tail -c1 "${file}" | wc -l) -eq 0 ]]; then
              >&2 echo "[warning] ${file} doesn't end with a linebreak."
              >&2 echo "          This will be fixed automatically."
              echo "" >> "${file}"
            fi
          done
      - name: Generate whitelist_readable.md
        shell: bash
        run: |
          rm -f whitelist_readable.md
          for file in $(find src -type f -name "*.txt" -print | sort -h); do
            heading=$(sed "s/_/ /g; s/\<./\U&/g" <<< "${file:4:-4}")
            for w in "a" "an" "the" "and" "or" "of" "for" "with"; do
              heading=$(sed "s/ ${w^} / ${w} /g" <<< "${heading}")
            done
            echo "# ${heading}" >> whitelist_readable.md
            cat "${file}" | while read line; do
              if [[ "${line// }" == "" ]]; then
                echo "" >> whitelist_readable.md
              elif [[ "${line:0:1}" == "#" ]]; then
                echo "#${line}" >> whitelist_readable.md
              else
                echo "- ${line}" >> whitelist_readable.md
              fi
            done
            echo "" >> whitelist_readable.md
          done
      - name: Generate whitelist.txt
        shell: bash
        run: |
          rm -f whitelist.txt
          for file in $(find src -type f -name "*.txt" -print | sort -h); do
            cat "${file}" | while read line; do
              if [[ "${line// }" == "" ]]; then
                continue
              elif [[ "${line:0:1}" != "#" ]]; then
                echo "*.$(sed "s/^*.//" <<< "${line}")/*" >> whitelist.txt
              fi
            done
          done
          echo "" >> whitelist.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update whitelist
